spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
client:
  base-url: "https://run.mocky.io"
logging:
  level:
    org.springframework: INFO
    com.workshop.sport: DEBUG
    org:
      springframework:
        data:
          r2dbc: DEBUG
